package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import Database.database;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

 
/**
 *
 * @author advan
 */
public class PusatAdmin extends javax.swing.JFrame {
    
    private Connection conn;
    
    public PusatAdmin() {
        initComponents();
        conn = database.getConnetion();
        getDataKasir();
        getDataProduk();
    }
    
    private void resetFormProduk() {
    txtProduk.setText("");
    txtHarga.setText("");
    comboboxStok.setSelectedIndex(0);
    comboboxP.setSelectedIndex(0);
    }
    
public void getDataKasir() {
    DefaultTableModel model = (DefaultTableModel) tbl_kasir.getModel();
    model.setRowCount(0);
    
    try {
        String sql = "SELECT * FROM kasir";
        PreparedStatement st = conn.prepareStatement(sql);
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_admin"),
                rs.getString("username"),
                rs.getString("password"),
                rs.getString("posisi")
            });
        }
        
        rs.close();
        st.close();
    } catch (Exception e) {
        e.printStackTrace();
        Logger.getLogger(PusatAdmin.class.getName()).log(Level.SEVERE, null, e);
    }
}

public void getDataProduk() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Produk");
    model.addColumn("Nama Produk");
    model.addColumn("Harga");
    model.addColumn("Stok");
    model.addColumn("Kategori");

    try {
        String sql = "SELECT * FROM produk";
        Statement st = database.getConnetion().createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_produk"),
                rs.getString("nama_produk"),
                rs.getDouble("harga"),
                rs.getString("stok"),
                rs.getString("kategori")
            });
        }
        tbl_produk.setModel(model);
        rs.close();
        st.close();
    } catch (Exception e) {
        e.printStackTrace();
        Logger.getLogger(PusatAdmin.class.getName()).log(Level.SEVERE, null, e);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kasir = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produk = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        t_posisi = new javax.swing.JLabel();
        comboboxK = new javax.swing.JComboBox<>();
        btnTambahK = new javax.swing.JButton();
        btnPerbaruiK = new javax.swing.JButton();
        btnBatalK = new javax.swing.JButton();
        btnHapusK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDKasir = new javax.swing.JTextField();
        t_nama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        t_pass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        t_produk = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboboxP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIDProduk = new javax.swing.JTextField();
        comboboxStok = new javax.swing.JComboBox<>();
        bntTambahP = new javax.swing.JButton();
        btnPerbaruiP = new javax.swing.JButton();
        btnBatalP = new javax.swing.JButton();
        btnHapusP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Pusat Admin");

        tbl_kasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Password", "Posisi"

            }
        ));
        tbl_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kasirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_kasir);

        tbl_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_produkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_produk);

        t_posisi.setText("Posisi");

        comboboxK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasir", "Admin" }));

        btnTambahK.setText("Tambah");
        btnTambahK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKActionPerformed(evt);
            }
        });

        btnPerbaruiK.setText("Perbarui");
        btnPerbaruiK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiKActionPerformed(evt);
            }
        });

        btnBatalK.setText("Batal");
        btnBatalK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKActionPerformed(evt);
            }
        });

        btnHapusK.setText("Hapus");
        btnHapusK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Pengaturan Kasir");

        jLabel2.setText("ID Kasir");

        t_nama.setText("Nama");

        t_pass.setText("Password");

        t_produk.setText("Produk");

        jLabel10.setText("Harga");

        jLabel11.setText("Kategori");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Pengaturan Menu");

        comboboxP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));

        jLabel6.setText("ID Produk");

        jLabel12.setText("Stock");

        txtIDProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProdukActionPerformed(evt);
            }
        });

        comboboxStok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak tersedia" }));
        comboboxStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxStokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboboxStok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIDProduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(t_produk)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(txtProduk)
                            .addComponent(txtHarga)
                            .addComponent(comboboxP, 0, 344, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_produk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass)
                    .addComponent(comboboxK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIDKasir)
                    .addComponent(txtNama)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(t_nama)
                    .addComponent(t_pass)
                    .addComponent(t_posisi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambahK)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerbaruiK)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatalK)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusK)))
                .addGap(35, 35, 35))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_posisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahK)
                    .addComponent(btnPerbaruiK)
                    .addComponent(btnBatalK)
                    .addComponent(btnHapusK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bntTambahP.setText("Tambah");
        bntTambahP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTambahPActionPerformed(evt);
            }
        });

        btnPerbaruiP.setText("Perbarui");
        btnPerbaruiP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiPActionPerformed(evt);
            }
        });

        btnBatalP.setText("Batal");
        btnBatalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPActionPerformed(evt);
            }
        });

        btnHapusP.setText("Hapus");
        btnHapusP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPerbaruiP)
                                    .addComponent(bntTambahP)
                                    .addComponent(btnBatalP)
                                    .addComponent(btnHapusP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bntTambahP)
                                .addGap(18, 18, 18)
                                .addComponent(btnPerbaruiP)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatalP)
                                .addGap(111, 111, 111)
                                .addComponent(btnHapusP)
                                .addGap(40, 40, 40))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO kasir (username, password, posisi) VALUES (?, ?, ?)";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtNama.getText());
        st.setString(2, txtPass.getText());
        st.setString(3, comboboxK.getSelectedItem().toString());
        st.executeUpdate();
        st.close();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        getDataKasir();
        resetFormKasir();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
    }
    }//GEN-LAST:event_btnTambahKActionPerformed

    private void btnPerbaruiKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiKActionPerformed
        // TODO add your handling code here:     
         int selectedRow = tbl_kasir.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah!");
        return;
    }

    int id = (int) tbl_kasir.getValueAt(selectedRow, 0); // assuming 0 is the id_admin column

    try {
        String sql = "UPDATE kasir SET username = ?, password = ?, posisi = ? WHERE id_admin = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtNama.getText());
        st.setString(2, txtPass.getText());
        st.setString(3, comboboxK.getSelectedItem().toString());
        st.setInt(4, id); // WHERE id_admin = ?

        st.executeUpdate();
        st.close();

        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        getDataKasir();
        resetFormKasir();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mengubah data");
    }
    }//GEN-LAST:event_btnPerbaruiKActionPerformed

    private void txtIDProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProdukActionPerformed

    private void tbl_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kasirMouseClicked
        // TODO add your handling code here:
        int row = tbl_kasir.getSelectedRow();
        txtNama.setText(tbl_kasir.getValueAt(row, 1).toString());
        txtPass.setText(tbl_kasir.getValueAt(row, 2).toString());
        comboboxK.setSelectedItem(tbl_kasir.getValueAt(row, 3).toString());
    
    }//GEN-LAST:event_tbl_kasirMouseClicked

    private void btnBatalKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKActionPerformed
        // TODO add your handling code here:
        resetFormKasir();
    }//GEN-LAST:event_btnBatalKActionPerformed

    private void btnHapusKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKActionPerformed
        // TODO add your handling code here:
         int selectedRow = tbl_kasir.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
        return;
    }

    int id = (int) tbl_kasir.getValueAt(selectedRow, 0); // assuming column 0 = id_admin

    try {
        String sql = "DELETE FROM kasir WHERE id_admin = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setInt(1, id);
        st.executeUpdate();
        st.close();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        getDataKasir();
        resetFormKasir();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menghapus data");
    }
    }//GEN-LAST:event_btnHapusKActionPerformed

    private void btnBatalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPActionPerformed
        // TODO add your handling code here:
        resetFormProduk();
    }//GEN-LAST:event_btnBatalPActionPerformed

    private void bntTambahPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTambahPActionPerformed
        // TODO add your handling code here:
        try {
    String sql = "INSERT INTO produk (nama_produk, harga, stok, kategori) VALUES (?, ?, ?, ?)";
    PreparedStatement st = conn.prepareStatement(sql);
    st.setString(1, txtProduk.getText());
    st.setDouble(2, Double.parseDouble(txtHarga.getText()));
    st.setString(3, comboboxStok.getSelectedItem().toString());
    st.setString(4, comboboxP.getSelectedItem().toString());
    st.executeUpdate();
    st.close();

    JOptionPane.showMessageDialog(this, "Data produk berhasil ditambahkan.");
    getDataProduk(); // refresh table
    resetFormProduk();
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menambahkan data produk.");
}

    }//GEN-LAST:event_bntTambahPActionPerformed

    private void comboboxStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxStokActionPerformed

    private void btnHapusPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPActionPerformed
        // TODO add your handling code here:
        try {
    int selectedRow = tbl_produk.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.");
        return;
    }

    int idProduk = Integer.parseInt(tbl_produk.getValueAt(selectedRow, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM produk WHERE id_produk=?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setInt(1, idProduk);
        st.executeUpdate();
        st.close();

        JOptionPane.showMessageDialog(this, "Data produk berhasil dihapus.");
        getDataProduk();
        resetFormProduk();
    }
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menghapus data produk.");
}
    }//GEN-LAST:event_btnHapusPActionPerformed

    private void tbl_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_produkMouseClicked
        // TODO add your handling code here:
    int row = tbl_produk.getSelectedRow();
        txtProduk.setText(tbl_produk.getValueAt(row, 1).toString());
        txtHarga.setText(tbl_produk.getValueAt(row, 2).toString());
        comboboxStok.setSelectedItem(tbl_produk.getValueAt(row, 3).toString());
        comboboxP.setSelectedItem(tbl_produk.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbl_produkMouseClicked

    private void btnPerbaruiPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiPActionPerformed
        // TODO add your handling code here:
        try {
    int selectedRow = tbl_produk.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diupdate.");
        return;
    }

    int idProduk = Integer.parseInt(tbl_produk.getValueAt(selectedRow, 0).toString());

    String sql = "UPDATE produk SET nama_produk=?, harga=?, stok=?, kategori=? WHERE id_produk=?";
    PreparedStatement st = conn.prepareStatement(sql);
    st.setString(1, txtProduk.getText());
    st.setDouble(2, Double.parseDouble(txtHarga.getText()));
    st.setString(3, comboboxStok.getSelectedItem().toString());
    st.setString(4, comboboxP.getSelectedItem().toString());
    st.setInt(5, idProduk);
    st.executeUpdate();
    st.close();

    JOptionPane.showMessageDialog(this, "Data produk berhasil diupdate.");
    getDataProduk();
    resetFormProduk();
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal mengupdate data produk.");
}
    }//GEN-LAST:event_btnPerbaruiPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PusatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PusatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PusatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PusatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PusatAdmin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTambahP;
    private javax.swing.JButton btnBatalK;
    private javax.swing.JButton btnBatalP;
    private javax.swing.JButton btnHapusK;
    private javax.swing.JButton btnHapusP;
    private javax.swing.JButton btnPerbaruiK;
    private javax.swing.JButton btnPerbaruiP;
    private javax.swing.JButton btnTambahK;
    private javax.swing.JComboBox<String> comboboxK;
    private javax.swing.JComboBox<String> comboboxP;
    private javax.swing.JComboBox<String> comboboxStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel t_nama;
    private javax.swing.JLabel t_pass;
    private javax.swing.JLabel t_posisi;
    private javax.swing.JLabel t_produk;
    private javax.swing.JTable tbl_kasir;
    private javax.swing.JTable tbl_produk;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDKasir;
    private javax.swing.JTextField txtIDProduk;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtProduk;
    // End of variables declaration//GEN-END:variables

    
    private void resetFormKasir() {
    txtNama.setText("");
    txtPass.setText("");
    comboboxK.setSelectedIndex(0);
    }}
